import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import Modal from '../components/Modal'
import Navbar from '../components/Navbar'
import Stock from '../components/Stock'



const Home: NextPage = () => {

  const [modal, setModal] = useState(false)
  console.log(modal)
  return (
    <div>
      <Head>
        <title>Carrito de Compras</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar/>
        <Stock setModal={setModal}/>
        {
        modal?
        <Modal setModal={setModal}/>
        :
        <span></span>
        }
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export default Home
