import type { NextPage } from 'next'
import Head from 'next/head'
import Modal from '../components/Modal'
import Navbar from '../components/Navbar'
import Stock from '../components/Stock'
import { GlobalContext } from '../context/context'
import { useContext } from 'react'



const Home: NextPage = () => {

  const {state} = useContext(GlobalContext)

  console.log(state)
  return (
    <div>
      <Head>
        <title>Tienda</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mbrishoppingcart.ico" />
      </Head>

      <main>
        <Navbar/>
        <Stock/>
        {
        state?
        <Modal/>
        :
        <span></span>
        }
      </main>

      <footer className="flex flex-col justify-center items-center bg-violet-600 h-32 mt-4">
        <div className='text-lg'>
          <h1>© Pedro Fernandez </h1>
        </div>
        <div className=' flex flex-col justify-center items-center mt-3'>
          <a href="https://nextjs.org/" target="_blank" rel='noopener noreferrer'>Nextjs</a>
          <a href="https://tailwindcss.com/" target="_blank" rel='noopener noreferrer'>Tailwind</a>
        </div>
      </footer>
    </div>
  )
}

export default Home
